package main

// The catalog is deliberately separate from seed mechanics so that the
// curriculum can be reviewed as data. Each pattern has one core map sketch for
// each supported engine; implementation writeups remain user-owned.

type seedEngine struct {
	slug, name, notes string
}

var seedEngines = []seedEngine{
	{slug: "valkey", name: "Valkey", notes: "Redis-compatible data-structure server. Strings and counters, expiration, lists, sorted sets, streams, Lua for atomic composition, and configurable persistence. Reference material often says Redis; the primitives are compatible."},
	{slug: "sqlite", name: "SQLite", notes: "Embedded transactional SQL. Tables, UNIQUE and PRIMARY KEY constraints, indexes, transactions, WAL mode, and triggers. Expiry and cross-process queue semantics are application conventions."},
	{slug: "postgres", name: "PostgreSQL", notes: "Server-side MVCC SQL. Row locks, FOR UPDATE SKIP LOCKED, advisory locks, LISTEN/NOTIFY, INSERT ... ON CONFLICT, sequences, and rich indexes support transactional implementations."},
}

const valkeyRestartAssumption = "For every restart guarantee here: use AOF with appendfsync always, disable eviction for durable keys, and use one primary; this does not promise lossless failover."

func durableValkeySketch(primitives string) string {
	return primitives + " " + valkeyRestartAssumption
}

type seedPattern struct {
	slug, name, family, explanation, useCases string
	curriculumOrder                           int
	invariants                                []string
	readings                                  []Reading
	valkey, sqlite, postgres                  string
}

var seedPatterns = []seedPattern{
	{
		slug: "counter", name: "Atomic counter", family: "counting", curriculumOrder: 1,
		explanation: "Many callers add to one number without a read-modify-write race. The mutation and returned value are one atomic store operation.",
		useCases:    "Page views, quota consumption, inventory deltas, and metrics updated by concurrent HTTP requests.",
		invariants:  []string{"No increment is lost under concurrent writers.", "Each successful increment returns a value consistent with one serial order."},
		readings:    []Reading{{"Valkey INCR command", "https://valkey.io/commands/incr/"}, {"PostgreSQL UPDATE", "https://www.postgresql.org/docs/current/sql-update.html"}},
		valkey:      durableValkeySketch("INCR/INCRBY performs the increment atomically."),
		sqlite:      "UPDATE counters SET value = value + ? WHERE key = ? in a transaction; RETURNING captures the mutation without an application read-modify-write; send success only after commit.",
		postgres:    "UPDATE ... SET value = value + $1 ... RETURNING value is atomic under row locking; use BIGINT and transaction boundaries appropriate to the caller.",
	},
	{
		slug: "optimistic-concurrency", name: "Optimistic concurrency / versioned writes", family: "state", curriculumOrder: 2,
		explanation: "A client updates only the version it read. A conflicting writer receives a conflict and must reread or abandon its change.",
		useCases:    "Editing profiles, documents, inventory records, and HTTP APIs using ETags or explicit resource versions.",
		invariants:  []string{"A write succeeds only when its expected version is current.", "Two conflicting writes cannot both overwrite the same version.", "A successful write advances the version exactly once."},
		readings:    []Reading{{"PostgreSQL transaction isolation", "https://www.postgresql.org/docs/current/transaction-iso.html"}, {"SQLite isolation", "https://www.sqlite.org/isolation.html"}},
		valkey:      durableValkeySketch("Store value and version in a hash; WATCH/MULTI/EXEC or a Lua compare-and-set checks the expected version and writes value plus version atomically."),
		sqlite:      "UPDATE records SET body = ?, version = version + 1 WHERE id = ? AND version = ? in a transaction; zero affected rows is a conflict.",
		postgres:    "Use the same guarded UPDATE ... WHERE version = $expected RETURNING version; a transaction exposes conflict rather than silently replacing a newer row.",
	},
	{
		slug: "state-machine", name: "Guarded state machine", family: "state", curriculumOrder: 3,
		explanation: "A record moves only through declared transitions. Each request checks its source state while applying the transition, so concurrent or repeated requests have defined results.",
		useCases:    "Order, payment, approval, and job lifecycles where shipping twice or approving a cancelled item is invalid.",
		invariants:  []string{"Only declared state transitions succeed.", "A transition is guarded by the state observed at mutation time.", "Repeated transitions return the documented current-state result without a second effect."},
		readings:    []Reading{{"PostgreSQL explicit locking", "https://www.postgresql.org/docs/current/explicit-locking.html"}, {"SQLite CREATE TRIGGER", "https://www.sqlite.org/lang_createtrigger.html"}},
		valkey:      durableValkeySketch("A Lua script reads the current state, validates the transition table, and writes state plus transition record atomically."),
		sqlite:      "Use a guarded UPDATE WHERE state IN (...) in an IMMEDIATE transaction; a CHECK or trigger can reject impossible stored transitions.",
		postgres:    "Lock the row with SELECT ... FOR UPDATE or issue a guarded UPDATE; record the transition in the same transaction when auditability is required.",
	},
	{
		slug: "idempotency-key", name: "Idempotency key", family: "idempotency", curriculumOrder: 4,
		explanation: "A retry key is bound to the business effect and the stored HTTP outcome. Repeating the same request returns that outcome instead of merely winning a lock or creating another effect.",
		useCases:    "Payment, order, and provisioning APIs whose clients retry after a timeout or lost response.",
		invariants:  []string{"One idempotency key binds to one request identity and business effect.", "Concurrent and later retries return the stored outcome.", "The completed binding survives the promised restart boundary."},
		readings:    []Reading{{"Stripe idempotent requests", "https://docs.stripe.com/api/idempotent_requests"}, {"PostgreSQL INSERT ON CONFLICT", "https://www.postgresql.org/docs/current/sql-insert.html"}},
		valkey:      durableValkeySketch("A Lua workflow atomically creates an in-progress key, performs or records the effect in its atomic boundary, and stores status/body; do not use bare SET NX as the whole contract."),
		sqlite:      "In one transaction, insert a UNIQUE key row tied to the business row and final status/body; conflicts read the stored outcome, including after process restart.",
		postgres:    "A UNIQUE key row, business mutation, and response payload commit in one transaction; ON CONFLICT selects the previously completed outcome rather than repeating side effects.",
	},
	{
		slug: "inbox", name: "Inbox / idempotent consumer", family: "idempotency", curriculumOrder: 5,
		explanation: "A consumer records a delivery identity together with its business result before acknowledging it. Duplicate deliveries are harmless, while distinct deliveries remain distinct.",
		useCases:    "Webhook receivers, message consumers, and integrations with at-least-once delivery.",
		invariants:  []string{"A delivery identity is processed into its business effect at most once within the atomicity boundary.", "A duplicate delivery obtains the stored processing outcome.", "Distinct delivery identities are not collapsed."},
		readings:    []Reading{{"Valkey Streams", "https://valkey.io/topics/streams-intro/"}, {"PostgreSQL INSERT ON CONFLICT", "https://www.postgresql.org/docs/current/sql-insert.html"}},
		valkey:      durableValkeySketch("Use a Stream plus a Lua script that records the message ID and effect/outcome atomically; acknowledge only after that state is durable, and tolerate redelivery outside external side effects."),
		sqlite:      "A UNIQUE(message_id) inbox row, domain mutation, and outcome commit together; on conflict return the saved outcome before acknowledging the delivery.",
		postgres:    "Use an inbox table keyed by producer/message identity; transactionally write the domain effect and result, then acknowledge externally knowing redelivery can reread the result.",
	},
	{
		slug: "expiring-reservation", name: "Expiring reservation", family: "idempotency", curriculumOrder: 6,
		explanation: "A resource can be reserved by one holder until an explicit deadline. Completion atomically persists a completed state with the reservation token, so an expired holder cannot complete after another holder takes the resource.",
		useCases:    "Seat holds, inventory reservations, booking flows, and uniqueness claims that must release after abandonment.",
		invariants:  []string{"At most one unexpired reservation holds a resource.", "Expired pending reservations become available again.", "Completion persists a terminal completed state and requires the current reservation token, so it cannot be stolen."},
		readings:    []Reading{{"Valkey SET", "https://valkey.io/commands/set/"}, {"PostgreSQL range types", "https://www.postgresql.org/docs/current/rangetypes.html"}},
		valkey:      durableValkeySketch("A Lua script atomically creates a pending resource/token/deadline record; completion verifies its live token and changes it to a durable completed state, while only pending expired records are reclaimed."),
		sqlite:      "Store resource, token, expires_at, and status under a UNIQUE resource key; guarded transactions reclaim only expired rows and complete only the matching live token.",
		postgres:    "Use a unique reservation row; completion requires the matching token, pending state, and expires_at > clock_timestamp() after acquiring the row lock, then persists completed state in the same transaction; guarded takeover only reclaims expired pending rows.",
	},
	{
		slug: "fifo-queue", name: "Reliable FIFO work queue", family: "queueing", curriculumOrder: 7,
		explanation: "Workers claim committed eligible jobs in increasing enqueue sequence and explicitly acknowledge them. That defines claim order; concurrent completion order is intentionally not FIFO, and delivery remains at-least-once.",
		useCases:    "Email, media processing, and slow background work moved out of HTTP request handling.",
		invariants:  []string{"Each claim selects the minimum enqueue sequence among jobs eligible at that instant; recovered retries can reintroduce an earlier sequence.", "At most one worker holds a live claim for each job at a time.", "An unacknowledged claim is recoverable and no acknowledged job is reissued.", "External effects may duplicate; handlers need idempotency."},
		readings:    []Reading{{"Valkey lists", "https://valkey.io/topics/lists/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("A Lua enqueue assigns a committed sequence and appends to one ready list; a Lua claim moves only its head to processing and records owner/deadline, while recovery requeues by original sequence."),
		sqlite:      "A singleton queue_head row serializes committed enqueue sequence and minimum eligible claims in an IMMEDIATE transaction. Record owner token and deadline; acknowledgement checks the live token and marks complete. Under the same gate, requeue only expired unacknowledged claims by original sequence, replacing the token so stale acknowledgements fail.",
		postgres:    "Lock queue_head with SELECT FOR UPDATE to allocate committed enqueue_seq or claim the minimum eligible job; store owner token and deadline. A guarded acknowledgement requires the live token and persists completion. Recovery takes that gate and requeues only expired unacknowledged claims with a new token; do not use SKIP LOCKED for strict FIFO.",
	},
	{
		slug: "lease", name: "Lease", family: "coordination", curriculumOrder: 8,
		explanation: "A time-limited ownership record has one live holder. The holder may renew before expiry; after expiry another client can acquire it.",
		useCases:    "One active scheduler, a shard owner, or a temporary task claim when crashed owners must stop blocking progress.",
		invariants:  []string{"At most one unexpired owner holds a lease name.", "Only the holder token can renew or release its lease.", "An abandoned lease becomes acquirable after its deadline."},
		readings:    []Reading{{"Valkey EXPIRE", "https://valkey.io/commands/expire/"}, {"PostgreSQL explicit locking", "https://www.postgresql.org/docs/current/explicit-locking.html"}},
		valkey:      durableValkeySketch("SET name token NX PX acquires; Lua renews or releases only when token matches. Expiration is a liveness aid, not exactly-once protection."),
		sqlite:      "A leases table stores owner token and expires_at; IMMEDIATE guarded updates acquire expired rows and renew only matching tokens using a single clock policy.",
		postgres:    "A lease row protected by SELECT FOR UPDATE stores token and deadline; guarded UPDATE handles acquire/renew/release transactionally.",
	},
	{
		slug: "fencing-tokens", name: "Fencing tokens", family: "coordination", curriculumOrder: 9,
		explanation: "Each successful owner receives a monotonically increasing token. The protected resource rejects writes carrying a token older than the greatest token it accepted, preventing stale lease holders from mutating it.",
		useCases:    "Protecting a database row, object store write, or downstream service after a lease expires or a client pauses.",
		invariants:  []string{"Each new ownership grant has a greater fencing token.", "The protected resource rejects stale tokens.", "Issuing a token alone is insufficient; acceptance is checked at the protected mutation."},
		readings:    []Reading{{"PostgreSQL sequences", "https://www.postgresql.org/docs/current/functions-sequence.html"}, {"Valkey INCR", "https://valkey.io/commands/incr/"}},
		valkey:      durableValkeySketch("Lua grants INCR token t and atomically installs t as the protected resource's active fence during takeover; protected mutations accept active_fence <= t, allowing repeated writes by t and rejecting every older owner."),
		sqlite:      "The grant transaction increments a fence and installs it on the protected row; every protected UPDATE uses WHERE active_fence <= ? and retains/advances the fence, allowing repeated mutations by the active token but rejecting stale ones.",
		postgres:    "A locked counter allocates token t and the activation transaction writes t to the protected row; every protected UPDATE has WHERE active_fence <= $t, so the resource itself accepts repeated current-owner writes and rejects stale owners.",
	},
	{
		slug: "task-ownership", name: "Task ownership and recovery", family: "coordination", curriculumOrder: 10,
		explanation: "A task claim names its owner and deadline. Completion is guarded by that claim, while abandoned work becomes claimable after recovery.",
		useCases:    "Long-running jobs, deployment steps, and task runners that need visible ownership and crash recovery.",
		invariants:  []string{"A live task claim names exactly one owner token.", "Only the current owner can complete a task.", "Completed tasks remain complete.", "Expired or orphaned claims become safely claimable again."},
		readings:    []Reading{{"Valkey hashes", "https://valkey.io/topics/hashes/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("Use a hash for state/owner/deadline and Lua for claim, heartbeat, completion, and orphan recovery; external work is at-least-once and needs an idempotency identity."),
		sqlite:      "Tasks store state, owner token, and lease deadline; an IMMEDIATE transaction uses guarded state transitions for claim, completion, and expired-claim recovery.",
		postgres:    "Claim with an ordered SELECT FOR UPDATE SKIP LOCKED and guarded update; completion and recovery verify owner token and deadline in transactions.",
	},
	{
		slug: "semaphore", name: "Semaphore / bounded concurrency", family: "coordination", curriculumOrder: 11,
		explanation: "A fixed pool of permits bounds simultaneous work. A release is tied to its issued permit identity, and abandoned permits expire or are reclaimed.",
		useCases:    "Limiting costly reports, downstream API calls, database migrations, or per-tenant concurrent work.",
		invariants:  []string{"No more than N live permits exist.", "A permit is released at most once.", "A crashed holder's permit eventually returns to the pool."},
		readings:    []Reading{{"Valkey sorted sets", "https://valkey.io/topics/sorted-sets/"}, {"PostgreSQL advisory locks", "https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS"}},
		valkey:      durableValkeySketch("Lua counts unexpired permit IDs, atomically creates a token with deadline when below N, and makes release idempotent."),
		sqlite:      "Permit rows keyed by token carry expires_at; a transaction reaps expired permits, counts live ones, inserts at most one new token, and deletes only a matching token on release.",
		postgres:    "Use the same permit table with row locking or an advisory lock around count-and-insert; guarded token deletes make duplicate release harmless.",
	},
	{
		slug: "delayed-queue", name: "Delayed queue / scheduler", family: "queueing", curriculumOrder: 12,
		explanation: "Jobs become claimable at their due time. A transactional claim keeps concurrent schedulers from running the same due job twice.",
		useCases:    "Reminders, scheduled publication, timeout actions, and retry backoff.",
		invariants:  []string{"No job is claimed before its due time.", "Every due job eventually becomes claimable.", "At most one worker holds a live claim for a due job."},
		readings:    []Reading{{"Valkey sorted sets", "https://valkey.io/topics/sorted-sets/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("Store due timestamps in a sorted set; Lua atomically selects due members, removes or marks them claimed, and records recovery state."),
		sqlite:      "An indexed run_at and claim fields support an IMMEDIATE transaction that selects the earliest due unclaimed job then atomically marks its claim.",
		postgres:    "Index run_at and use SELECT ... FOR UPDATE SKIP LOCKED WHERE run_at <= now(); update the claim in the same transaction and recover timed-out claims.",
	},
	{
		slug: "retry-lifecycle", name: "Retry and dead-letter lifecycle", family: "queueing", curriculumOrder: 13,
		explanation: "A failed job records an atomic attempt count and next eligible time. It backs off before retrying, becomes dead-lettered after its limit, and can be redriven with a new controlled lifecycle.",
		useCases:    "Transient downstream failures, poison messages, and operational recovery after a bug fix.",
		invariants:  []string{"Retries do not run before their scheduled backoff.", "Attempt counting and state changes are atomic.", "A poison job stops retrying at its configured limit.", "Redrive is explicit and does not silently duplicate a completed effect."},
		readings:    []Reading{{"AWS exponential backoff and jitter", "https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("Lua increments attempts and moves failed jobs to a due-time sorted set or terminal dead-letter stream atomically; idempotent handlers cover external duplicate effects."),
		sqlite:      "Jobs store attempts, next_attempt_at, status, and redrive identity; transactions guard failure transitions, due claims, terminal dead-lettering, and explicit redrive.",
		postgres:    "Use the same lifecycle columns with guarded UPDATEs and SKIP LOCKED due claims; commit each attempt transition before any retry becomes eligible.",
	},
	{
		slug: "priority-queue", name: "Priority queue with fairness", family: "queueing", curriculumOrder: 14,
		explanation: "Three priority classes use weighted round robin: eight high, two normal, then one low claim whenever that class is nonempty. Each class is FIFO, so a continuously nonempty low class receives one claim in every eleven claims.",
		useCases:    "Urgent customer work mixed with batch jobs, schedulers, and support queues.",
		invariants:  []string{"The scheduler cycles eight high, two normal, and one low eligible claim when those classes are nonempty.", "Each priority class claims jobs in enqueue sequence.", "A continuously nonempty low class receives at least one claim in every eleven claims.", "At most one worker holds a live claim for each job."},
		readings:    []Reading{{"Valkey sorted sets", "https://valkey.io/topics/sorted-sets/"}, {"PostgreSQL ORDER BY", "https://www.postgresql.org/docs/current/queries-order.html"}},
		valkey:      durableValkeySketch("Keep FIFO lists per high/normal/low class and a shared 8:2:1 schedule cursor; Lua advances the cursor over empty classes, claims one head atomically, and records recovery state."),
		sqlite:      "FIFO sequence per priority plus a singleton 8:2:1 schedule cursor are updated in one IMMEDIATE transaction; it claims the selected nonempty class's lowest sequence with a token.",
		postgres:    "Lock the shared 8:2:1 schedule cursor, select and lock the lowest enqueue_seq in its selected nonempty class, then advance the cursor and record the claim in that transaction.",
	},
	{
		slug: "rate-limiter", name: "Comparative rate limiter", family: "rate-limiting", curriculumOrder: 15,
		explanation: "One HTTP contract exposes fixed-window, sliding-window, and token-bucket policies. The exercise compares their limits, refills, burst behavior, and concurrent admission decisions.",
		useCases:    "Per-user API quotas, login abuse protection, and protecting expensive endpoints.",
		invariants:  []string{"Fixed-window admission never exceeds its configured window count.", "Sliding-window admission accounts for requests across the moving interval.", "Token-bucket admission respects capacity and refill while permitting its configured burst.", "Concurrent admission decisions are atomic for every algorithm."},
		readings:    []Reading{{"Valkey INCR", "https://valkey.io/commands/incr/"}, {"PostgreSQL window functions", "https://www.postgresql.org/docs/current/tutorial-window.html"}},
		valkey:      durableValkeySketch("Lua implements all three: fixed-window counter with expiry; sliding-window timestamp sorted set with trim/count; token bucket with stored tokens and last_refill. Each script atomically admits or rejects."),
		sqlite:      "Transactions implement all three: bucketed counter rows; timestamp event rows pruned and counted over the interval; token row updated from elapsed time. A guarded write makes each admit decision atomic.",
		postgres:    "Transactions implement all three: ON CONFLICT fixed-window counters; indexed timestamp rows for sliding windows; a locked token row for refill/capacity. Return remaining allowance from the committed decision.",
	},
	{
		slug: "heartbeat", name: "Heartbeat and failure detector", family: "coordination", curriculumOrder: 16,
		explanation: "Workers renew a liveness record. The detector marks a silent worker suspected after a timeout, while re-registration uses an identity/epoch that prevents accidental duplicate live identities.",
		useCases:    "Worker pools, schedulers, consumer membership, and operational health views.",
		invariants:  []string{"A timely heartbeat keeps a worker live.", "A silent worker becomes suspected after the configured timeout.", "Recovery uses a new or validated epoch so two processes do not share one live identity."},
		readings:    []Reading{{"Valkey EXPIRE", "https://valkey.io/commands/expire/"}, {"PostgreSQL date/time functions", "https://www.postgresql.org/docs/current/functions-datetime.html"}},
		valkey:      durableValkeySketch("Heartbeat key stores worker ID plus epoch with TTL; Lua renews only a matching epoch and membership scans expire stale identities."),
		sqlite:      "A workers table stores identity, epoch, and last_seen; guarded transactions renew only the current epoch and queries classify timeout-based suspicion using one clock convention.",
		postgres:    "Use the same membership rows with transactional epoch compare-and-set; indexes on last_seen support detector scans and membership recovery.",
	},
	{
		slug: "leader-election", name: "Leader election", family: "coordination", curriculumOrder: 17,
		explanation: "Candidates compete for one renewable lease and attach fencing to leader work. On expiry another candidate can become visible leader; external side effects still require an idempotency boundary.",
		useCases:    "One active scheduler, singleton maintenance jobs, and a coordinator for a group of workers.",
		invariants:  []string{"At most one unexpired leader is visible.", "Only the current leader token renews leadership.", "Another candidate can take over after expiry.", "Leader actions use fencing where a stale leader could mutate protected state."},
		readings:    []Reading{{"Valkey SET", "https://valkey.io/commands/set/"}, {"PostgreSQL advisory locks", "https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS"}},
		valkey:      durableValkeySketch("Acquire a TTL lease with token and increment a fencing counter in Lua; activation installs the new fence on each leader-controlled resource, whose mutations accept that fence or later and reject older leaders."),
		sqlite:      "A leader row holds token, fence, and expires_at; guarded IMMEDIATE transactions acquire/renew it, while protected work validates the fence in its own mutation.",
		postgres:    "A transactional leader lease row provides durable visibility and fencing; advisory locks can coordinate sessions but do not replace persisted lease/fence checks for crash recovery.",
	},
	{
		slug: "notification-vs-delivery", name: "Ephemeral notification vs durable delivery", family: "messaging", curriculumOrder: 18,
		explanation: "Live subscribers receive ephemeral wake-up signals only while connected. Work that must survive disconnection is stored durably and can be read or replayed later.",
		useCases:    "Websocket updates, cache invalidation wakeups, and notifying workers that durable work is available.",
		invariants:  []string{"A connected subscriber receives notifications published while it is subscribed.", "A disconnected subscriber may miss an ephemeral notification.", "Required delivery is recovered from durable state, not inferred from notification receipt.", "Notifications do not promise exactly-once external effects."},
		readings:    []Reading{{"Valkey pub/sub", "https://valkey.io/topics/pubsub/"}, {"PostgreSQL NOTIFY", "https://www.postgresql.org/docs/current/sql-notify.html"}},
		valkey:      durableValkeySketch("PUBLISH/SUBSCRIBE supplies ephemeral wakeups; a Stream or durable key stores recoverable delivery state, and consumers reconcile it after reconnect."),
		sqlite:      "SQLite has no native cross-process pub/sub; write durable events in a transaction and use polling or an application notifier only as a wakeup hint.",
		postgres:    "LISTEN/NOTIFY wakes connected clients, while a durable events table is the delivery source of truth; clients query it after reconnect because notifications are not a queue.",
	},
	{
		slug: "outbox", name: "Transactional outbox", family: "messaging", curriculumOrder: 19,
		explanation: "A business mutation and an outgoing record share one durable transaction. A dispatcher may redeliver, so consumers must deduplicate the message identity rather than claiming exactly-once effects.",
		useCases:    "Domain events, transactional email, webhooks, and database-to-broker integration.",
		invariants:  []string{"Business state and its outbox record commit together or neither commits.", "Every committed outbox record is eventually delivered when the transport recovers and a fair dispatcher continues retrying.", "Dispatcher retries may redeliver; message identity supports idempotent consumption."},
		readings:    []Reading{{"AWS transactional outbox", "https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/transactional-outbox.html"}, {"PostgreSQL transactions", "https://www.postgresql.org/docs/current/tutorial-transactions.html"}},
		valkey:      durableValkeySketch("When Valkey is the business store, Lua writes domain state and a Stream record atomically; when it is only the transport, the SQL business transaction owns the outbox and publish is retried separately."),
		sqlite:      "Insert business rows and an outbox row with stable message ID in one SQLite transaction; a dispatcher claims rows and marks delivery separately, tolerating crash redelivery.",
		postgres:    "Commit business rows and outbox rows in one ACID transaction; dispatchers claim undelivered rows with SKIP LOCKED and publish idempotently by message ID.",
	},
	{
		slug: "saga", name: "Saga / compensating transaction", family: "messaging", curriculumOrder: 20,
		explanation: "A workflow spans stores that cannot share one transaction. Durable progress records completed steps, and each compensatable step has a defined compensating action after later failure.",
		useCases:    "Order fulfillment across payment, inventory, and shipping services; provisioning workflows across independent systems.",
		invariants:  []string{"Each step's success or failure is durably recorded.", "A partial failure triggers the required compensations in a defined order.", "Retries resume from durable progress and make step/compensation requests idempotent.", "The workflow does not claim one atomic transaction across independent stores."},
		readings:    []Reading{{"AWS saga patterns", "https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/saga-patterns.html"}, {"PostgreSQL transactions", "https://www.postgresql.org/docs/current/tutorial-transactions.html"}},
		valkey:      durableValkeySketch("A Valkey saga hash and Stream outbox record each step; commands to SQLite or PostgreSQL participants carry saga_id/step as an inbox key, so an ambiguous remote success is retried as the same command before compensation is emitted."),
		sqlite:      "SQLite saga, step, outbox, and inbox tables commit local progress together; its outbox sends stable saga_id/step commands to PostgreSQL and Valkey participants, whose duplicate deliveries return recorded outcomes before the next step or compensation.",
		postgres:    "PostgreSQL saga/step/outbox/inbox tables durably orchestrate commands to a Valkey reservation and SQLite worker; a timeout reissues the identical saga_id/step command, and compensation is emitted only from recorded step state.",
	},
	{
		slug: "durable-event-log", name: "Durable event log", family: "log", curriculumOrder: 21,
		explanation: "SQLite and PostgreSQL assign contiguous committed integer replay positions while a serialized log-head gate is held. Valkey uses its ordered unique Stream IDs, whose numeric values may have gaps. Clients replay the appropriate cursor in order.",
		useCases:    "Audit trails, event sourcing, change feeds, and replayable integrations.",
		invariants:  []string{"SQLite and PostgreSQL committed records have contiguous, unique integer positions in commit order.", "Valkey committed Stream records have strictly increasing unique replay IDs; numeric ID gaps are allowed.", "A client cursor is an exact committed SQL position or Stream ID and cannot skip a late committed record.", "The SQL committed position is not an independently allocated sequence value.", "Committed records survive restart according to the selected persistence configuration."},
		readings:    []Reading{{"Valkey Streams", "https://valkey.io/topics/streams-intro/"}, {"PostgreSQL sequences", "https://www.postgresql.org/docs/current/functions-sequence.html"}},
		valkey:      durableValkeySketch("Use one Stream and its server-assigned ID as the committed replay cursor; XADD serializes appends on the primary, and readers resume with IDs greater than their last processed ID."),
		sqlite:      "A singleton log_head row is updated in the same write transaction as the event insert: lock head, increment committed_position, insert event, then commit; readers resume WHERE position > cursor ORDER BY position.",
		postgres:    "SELECT the singleton log_head FOR UPDATE, increment and insert the event under that lock, then commit before another append obtains it; readers resume WHERE position > cursor ORDER BY position, never from a bare sequence.",
	},
	{
		slug: "consumer-checkpoints", name: "Consumer checkpoints / offsets", family: "log", curriculumOrder: 22,
		explanation: "A consumer stores completed progress durably. It advances past a record only after processing, so a crash may duplicate work but cannot silently skip an unprocessed hole.",
		useCases:    "Event projections, ETL, durable webhooks, and resumable importers.",
		invariants:  []string{"Checkpoint progress survives restart.", "A checkpoint cannot advance past an unprocessed record.", "Recovery may replay completed records but cannot lose records before the committed checkpoint."},
		readings:    []Reading{{"Valkey Streams", "https://valkey.io/topics/streams-intro/"}, {"PostgreSQL UPDATE", "https://www.postgresql.org/docs/current/sql-update.html"}},
		valkey:      durableValkeySketch("Consumer state records the last processed Stream ID and advances only after durable processing state; the next record is the next existing greater Stream ID, not a numerically adjacent ID, and pending entries are redelivered after failure."),
		sqlite:      "The durable-log cursor is the committed contiguous position from the log-head transaction; within one transaction apply the local effect and advance a checkpoint only from n to n+1, using an inbox for duplicate replay.",
		postgres:    "Lock the consumer checkpoint row, apply the record's idempotent projection, and advance only from committed position n to n+1 in that transaction; it never advances across a hole.",
	},
	{
		slug: "consumer-groups", name: "Consumer group", family: "log", curriculumOrder: 23,
		explanation: "A group divides records or partitions among workers, tracks live claims, and reassigns abandoned work. Acknowledgements advance group progress only after processing.",
		useCases:    "Scaling stream processing workers while preserving recoverable group progress.",
		invariants:  []string{"A record or partition has one live group owner at a time.", "Abandoned work becomes reassignable.", "Acknowledgements advance group progress only after the consumer's idempotent local effect commits.", "Redelivery is possible and consumers handle duplicates."},
		readings:    []Reading{{"Valkey Streams consumer groups", "https://valkey.io/topics/streams-intro/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("Use Stream consumer groups, pending entries, and claim/recovery commands; acknowledge after idempotent processing and reclaim idle pending messages."),
		sqlite:      "Group assignments, claims, and contiguous checkpoints live in tables; IMMEDIATE transactions assign unowned/expired work and acknowledge after local processing, while an inbox absorbs duplicate delivery.",
		postgres:    "Use partition/claim tables with leases and SELECT FOR UPDATE SKIP LOCKED; transactionally update processing state and group progress, then recover expired owners.",
	},
	{
		slug: "incremental-projection", name: "Incremental projection / read model", family: "state", curriculumOrder: 24,
		explanation: "A read model consumes a durable log through a recorded source position. Applying a record is idempotent, and rebuilding from the log produces the same derived state.",
		useCases:    "CQRS read models, dashboards, denormalized search data, and aggregate counters.",
		invariants:  []string{"Derived state identifies the source position it represents.", "Duplicate event application is harmless.", "A rebuild from the same log produces the same read model."},
		readings:    []Reading{{"PostgreSQL materialized views", "https://www.postgresql.org/docs/current/rules-materializedviews.html"}, {"Valkey Streams", "https://valkey.io/topics/streams-intro/"}},
		valkey:      durableValkeySketch("Consume a Stream and use Lua to atomically record applied event ID, update projection keys, and advance position."),
		sqlite:      "A transaction checks an applied_events identity, updates derived tables, and records the projection checkpoint together; rebuild truncates/recreates only derived state then replays the log.",
		postgres:    "In one transaction insert a unique applied-event marker, update the projection, and advance its source position; materialized views may help reads but do not replace replay bookkeeping.",
	},
	{
		slug: "snapshots-compaction", name: "Snapshots and log compaction", family: "log", curriculumOrder: 25,
		explanation: "A snapshot captures state at a known log position, allowing recovery from that snapshot plus later events. Compaction retains the data still required by the oldest consumer or snapshot policy.",
		useCases:    "Long-lived event logs, faster recovery, and bounded storage while preserving consumer replay guarantees.",
		invariants:  []string{"Snapshot state is tied to a precise included log position.", "Snapshot plus subsequent events restores the same state as full replay.", "Compaction does not remove records required by the oldest retained consumer or recovery policy."},
		readings:    []Reading{{"Valkey Streams trimming", "https://valkey.io/commands/xtrim/"}, {"PostgreSQL table partitioning", "https://www.postgresql.org/docs/current/ddl-partitioning.html"}},
		valkey:      durableValkeySketch("Store snapshot payload and last stream ID; compute a safe trim point from registered consumer/checkpoint minima, then XTRIM only below that policy boundary."),
		sqlite:      "Snapshots store serialized state and included position; a transaction records consumer minima and deletes only log rows older than the safe minimum and covered snapshot.",
		postgres:    "Persist snapshot metadata and consumer offsets; partition or delete event rows only below the computed safe retention point, retaining data necessary for recovery and lagging consumers.",
	},
	{
		slug: "cache-consistency", name: "Cache consistency and stampede protection", family: "caching", curriculumOrder: 26,
		explanation: "A cache serves fresh values until fresh_until, then may serve stale for a fixed 30-second grace only when refresh fails. One live refresh owner holds a renewable fenced lease and is the only owner allowed to publish a refresh.",
		useCases:    "Hot read models, API responses, rendered pages, and expensive computed aggregates.",
		invariants:  []string{"A value is fresh only through fresh_until.", "Concurrent misses share the current live owner's refresh outcome; only one live refresh lease owner may publish for a key.", "On refresh failure, stale is served only through stale_until = fresh_until + 30 seconds; after that the request fails.", "A fenced publication rejects an expired or replaced refresh owner."},
		readings:    []Reading{{"Valkey EXPIRE", "https://valkey.io/commands/expire/"}, {"PostgreSQL advisory locks", "https://www.postgresql.org/docs/current/explicit-locking.html#ADVISORY-LOCKS"}},
		valkey:      durableValkeySketch("Value records carry fresh_until and stale_until=fresh_until+30s; Lua grants a renewable refresh token/fence, renews only its live owner, and publishes only if its token/fence matches and its lease is unexpired; waiters share that refresh outcome, otherwise the replaced owner cannot overwrite the value."),
		sqlite:      "A cache row stores value, fresh_until, stale_until=fresh_until+30s, refresh token/fence, and lease deadline; an IMMEDIATE transaction grants/renews one owner and guarded publication verifies token/fence and unexpired deadline; waiters share its refresh outcome, with errors after the stale grace.",
		postgres:    "A locked cache row stores the same 30-second grace and refresh token/fence; a transaction grants or renews one owner and publication UPDATE verifies token/fence and unexpired deadline; waiters share the refresh outcome, so an expired owner cannot publish over a replacement.",
	},
	{
		slug: "distributed-id", name: "Distributed ID generation", family: "counting", curriculumOrder: 27,
		explanation: "Each generator leases a durable block of 1,024 integer IDs before issuing any from it. Leased and abandoned IDs are never reused; IDs are unique and increase within one generator, but return order is not globally ordered.",
		useCases:    "Orders, events, public resource IDs, and log entries created by several workers.",
		invariants:  []string{"IDs are unique under concurrent generation and restart.", "A generator issues IDs in increasing order under local serialization; concurrent response arrival order is not promised.", "Leases are 1,024 IDs and neither crash-abandoned nor partially used ranges are reused.", "Allocation fails before the signed 64-bit counter would overflow; wall-clock changes do not affect these integer ranges. There is no global return-order or clock-order promise."},
		readings:    []Reading{{"PostgreSQL sequences", "https://www.postgresql.org/docs/current/functions-sequence.html"}, {"Valkey INCR", "https://valkey.io/commands/incr/"}},
		valkey:      durableValkeySketch("INCRBY 1024 durably reserves [high-1023, high]; a generator persists its next value before returning it and discards the unused remainder after restart, never reclaiming an abandoned block."),
		sqlite:      "In an IMMEDIATE transaction, UPDATE id_head SET value=value+1024 WHERE value <= 9223372036854774783 RETURNING value; zero rows is exhaustion. CHECK(typeof(value)='integer' AND value>=0) prevents REAL overflow promotion. Record the durable high watermark before use, persist next_id before issue, and discard any remainder on restart.",
		postgres:    "Lock a singleton id_head row, advance it by 1,024, and commit the lease before issue; persist next_id before return and discard unused lease values after restart, without claiming sequence or clock order.",
	},
	{
		slug: "sharded-counter", name: "Sharded/hot-key counter", family: "counting", curriculumOrder: 28,
		explanation: "Each operation hashes its identity modulo 64 to choose a deterministic shard, avoiding one hot key. Valkey totals are eventually consistent shard sums; SQLite and PostgreSQL totals are exact within one read transaction. Retries use the operation identity to avoid double counting.",
		useCases:    "Very hot page metrics, reactions, quotas, and counters whose one-key write rate is a bottleneck.",
		invariants:  []string{"Each operation identity chooses one of 64 shards by hash modulo 64.", "A Valkey total is an eventually consistent sum; SQLite and PostgreSQL totals are exact in one read-transaction snapshot.", "Retrying one logical increment does not double count it.", "Concurrent shard updates preserve each shard's atomicity."},
		readings:    []Reading{{"Valkey INCR", "https://valkey.io/commands/incr/"}, {"PostgreSQL INSERT ON CONFLICT", "https://www.postgresql.org/docs/current/sql-insert.html"}},
		valkey:      durableValkeySketch("Hash operation ID to a shard; Lua records a dedup identity and increments that shard atomically, while total sums shards with explicitly eventual consistency unless a snapshot protocol is added."),
		sqlite:      "A transaction inserts UNIQUE(operation_id) then increments a selected shard row; totals sum shards in one read transaction for a consistent local snapshot.",
		postgres:    "Insert the operation identity ON CONFLICT DO NOTHING RETURNING operation_id; increment hash(operation_id) mod 64 only from the returned inserted row (for example a data-modifying CTE). Duplicates return no row and cause no increment. Commit identity and increment together; SUM sees one transaction snapshot.",
	},
	{
		slug: "partition-rebalancing", name: "Partition assignment and rebalancing", family: "coordination", curriculumOrder: 29,
		explanation: "Registered workers receive non-overlapping partition assignments. Membership changes produce a new assignment epoch, and workers or protected resources reject stale epochs.",
		useCases:    "Sharded queues, stream partitions, crawler ranges, and worker pools with changing membership.",
		invariants:  []string{"A partition has at most one live assignment in an epoch.", "Membership changes eventually create a non-overlapping redistribution.", "Assignments carry an epoch or fence that rejects stale workers.", "Ownership expiry and reassignment tolerate crash recovery."},
		readings:    []Reading{{"Valkey sets", "https://valkey.io/topics/sets/"}, {"PostgreSQL SELECT locking clause", "https://www.postgresql.org/docs/current/sql-select.html"}},
		valkey:      durableValkeySketch("Store members with TTL and assignments with epoch/fence; Lua computes or applies a deterministic assignment and atomically fences replaced owners."),
		sqlite:      "Membership, assignment epoch, owner token, and lease deadline live in tables; an IMMEDIATE transaction serializes rebalance and guarded worker updates reject stale epochs.",
		postgres:    "Lock membership/assignment rows to compute a new epoch, update all partitions transactionally, and require each protected partition mutation to match current epoch and owner token.",
	},
}
